const express = require('express');
const fs = require('fs');
const os = require('os');
const path = require('path');
const app = express();
const port = 3000;

const COUNTER_FILE = path.join(__dirname, 'order_counter.json');

// Helper to load persistent order counter from disk
function loadOrderCounter() {
    try {
        if (fs.existsSync(COUNTER_FILE)) {
            const data = fs.readFileSync(COUNTER_FILE, 'utf8');
            const parsed = JSON.parse(data);
            if (typeof parsed.orderCounter === 'number' && parsed.orderCounter > 0) {
                return parsed.orderCounter;
            }
        }
    } catch (err) {
        console.error("Error reading order_counter.json:", err);
    }
    return 10;
}

// Helper to save persistent order counter to disk
function saveOrderCounter(count) {
    try {
        fs.writeFileSync(COUNTER_FILE, JSON.stringify({ orderCounter: count, updatedAt: new Date().toISOString() }, null, 2));
    } catch (err) {
        console.error("Error writing order_counter.json:", err);
    }
}

let orderCounter = loadOrderCounter();
console.log(`[Order System] Persistent order counter initialized at Order #${orderCounter}`);

// Serve static monorepo files (Root hub, /printer/, /lights/)
app.use(express.static(__dirname));

app.get('/order-info', (req, res) => {
    res.json({ orderCounter });
});

// Shared execution engine for both HTTP POST and Firebase Cloud Queue
async function executePrintJob(rawImageData) {
    console.log(`Received Order #${orderCounter}: ${rawImageData.length} image bytes`);
    
    // Construct ESC/POS Header (Initialize) and Footer (Feeds, Cut, Reset)
    const initCmd = Buffer.from([0x1B, 0x40]); // Init
    const cutCmd = Buffer.from([
        0x0A, 0x0A, 0x0A, 0x0A, // Extra feeds
        0x1D, 0x56, 0x41, 0x00, // Cut paper
        0x1B, 0x40              // Reset printer state (ESC @) to clear buffer and restore default state
    ]);
    
    // Combine init + raw image + cut
    const finalPrintData = Buffer.concat([initCmd, rawImageData, cutCmd]);
    
    const printedOrder = orderCounter;
    orderCounter++;
    saveOrderCounter(orderCounter);
    
    try {
        await printViaUsb(finalPrintData);
        return { success: true, message: `Order #${printedOrder} Printed!`, nextOrder: orderCounter };
    } catch (error) {
        console.error('Print failed:', error);
        
        // Fallback for Raspberry Pi if direct USB library fails (uses system device file)
        const linuxPrinterPath = '/dev/usb/lp0';
        if (fs.existsSync(linuxPrinterPath)) {
            try {
                const fd = fs.openSync(linuxPrinterPath, 'w');
                const CHUNK_SIZE = 2048;
                for (let offset = 0; offset < finalPrintData.length; offset += CHUNK_SIZE) {
                    const chunk = finalPrintData.slice(offset, offset + CHUNK_SIZE);
                    fs.writeSync(fd, chunk);
                    const stop = Date.now() + 15;
                    while (Date.now() < stop) {}
                }
                fs.closeSync(fd);
                console.log('Successfully sent to printer via fallback /dev/usb/lp0');
                return { success: true, message: `Order #${printedOrder} Printed via fallback!`, nextOrder: orderCounter };
            } catch (fallbackError) {
                console.error('Fallback failed:', fallbackError);
            }
        }
        throw error;
    }
}

// Accept raw binary data for printing (ESC/POS payload generated by the frontend)
app.post('/print', express.raw({ type: 'application/octet-stream', limit: '10mb' }), async (req, res) => {
    try {
        const result = await executePrintJob(req.body);
        res.status(200).send(result);
    } catch (error) {
        res.status(500).send({ success: false, message: 'Print failed: ' + error.message });
    }
});

// Optional Firebase Cloud Queue Listener for GitHub Pages mode
function initFirebaseSubscriber() {
    const serviceAccountPath = path.join(__dirname, 'firebase-service-account.json');
    const webConfigPath = path.join(__dirname, 'firebase-config.json');
    
    let db = null;
    
    if (fs.existsSync(serviceAccountPath)) {
        try {
            const firebaseAdmin = require('firebase-admin');
            const serviceAccount = require(serviceAccountPath);
            firebaseAdmin.initializeApp({
                credential: firebaseAdmin.credential.cert(serviceAccount)
            });
            db = firebaseAdmin.firestore();
            console.log("✓ [Firebase] Admin SDK initialized with service account key!");
        } catch (e) {
            console.error("Failed to initialize firebase-admin:", e.message);
        }
    } else if (fs.existsSync(webConfigPath)) {
        try {
            const { initializeApp } = require('firebase/app');
            const { getFirestore, collection, query, where, onSnapshot, doc, setDoc } = require('firebase/firestore');
            const cfg = JSON.parse(fs.readFileSync(webConfigPath, 'utf8'));
            const fbApp = initializeApp(cfg);
            db = getFirestore(fbApp);
            console.log("✓ [Firebase] Web SDK initialized for Raspberry Pi subscriber!");
        } catch (e) {
            console.error("Failed to initialize firebase web SDK:", e.message);
        }
    }

    if (!db) {
        console.log("ℹ Firebase subscriber not active (No firebase-service-account.json or firebase-config.json found). Running in local HTTP mode.");
        return;
    }

    console.log("⚡ [Cloud Queue] Subscribed to Firestore collection 'print_jobs'...");

    // Sync order counter to Firestore
    const syncCounterToFirestore = async (count) => {
        try {
            if (db.collection) {
                await db.collection('order_counter').doc('main').set({ orderCounter: count, updatedAt: new Date().toISOString() });
            }
        } catch (err) {
            console.error("Error updating Firestore order_counter:", err.message);
        }
    };

    syncCounterToFirestore(orderCounter);

    let isProcessing = false;
    
    if (db.collection) {
        db.collection('print_jobs').where('status', '==', 'pending').onSnapshot(async (snapshot) => {
            if (snapshot.empty || isProcessing) return;
            isProcessing = true;

            for (const docSnapshot of snapshot.docs) {
                const data = docSnapshot.data();
                if (!data || !data.payload) continue;

                console.log(`[Cloud Queue] Processing Order #${data.orderNumber || '?'} (Doc ID: ${docSnapshot.id})`);
                const rawImageData = Buffer.from(data.payload, 'base64');
                
                try {
                    const result = await executePrintJob(rawImageData);
                    await syncCounterToFirestore(result.nextOrder);
                    // Immediately delete document from cloud after printing (zero persistent storage needed)
                    await docSnapshot.ref.delete();
                    console.log(`[Cloud Queue] Job ${docSnapshot.id} completed & deleted from cloud queue!`);
                } catch (err) {
                    console.error(`[Cloud Queue] Job ${docSnapshot.id} failed:`, err);
                    await docSnapshot.ref.update({ status: 'error', errorMsg: err.message });
                }
            }
            isProcessing = false;
        });
    }
}

initFirebaseSubscriber();

const { WebUSB } = require('usb');
const customWebUSB = new WebUSB({ allowAllDevices: true });

async function printViaUsb(data) {
    const devices = await customWebUSB.getDevices();
    let printer = null;

    for (const d of devices) {
        if (d.vendorId === 0x1FC9 && d.productId === 0x2016) {
            printer = d;
            break;
        }
    }

    if (!printer && devices.length > 0) {
        for (const d of devices) {
            if (d.configuration && d.configuration.interfaces) {
                const hasPrinterInterface = d.configuration.interfaces.some(i => 
                    i.alternate && i.alternate.interfaceClass === 7
                );
                if (hasPrinterInterface) {
                    printer = d;
                    break;
                }
            }
        }
        if (!printer) printer = devices[0];
    }

    if (!printer) {
        throw new Error('Could not find USB printer');
    }

    await printer.open();
    
    if (printer.configuration === null) {
        await printer.selectConfiguration(1);
    }
    
    await printer.claimInterface(0);
    
    const endpoints = printer.configuration.interfaces[0].alternate.endpoints;
    const outEndpoint = endpoints.find(e => e.direction === 'out');
    
    if (!outEndpoint) {
        throw new Error('No OUT endpoint found on printer');
    }

    const CHUNK_SIZE = 2048;
    const CHUNK_DELAY_MS = 20;

    for (let offset = 0; offset < data.length; offset += CHUNK_SIZE) {
        const chunk = data.slice(offset, offset + CHUNK_SIZE);
        await printer.transferOut(outEndpoint.endpointNumber, chunk);
        if (offset + CHUNK_SIZE < data.length) {
            await new Promise(resolve => setTimeout(resolve, CHUNK_DELAY_MS));
        }
    }
    console.log("Successfully sent to USB printer in chunked transfers!");
    
    try {
        await printer.releaseInterface(0);
    } catch (e) {}
    await printer.close();
}

function getLocalIp() {
    const interfaces = os.networkInterfaces();
    for (const name of Object.keys(interfaces)) {
        for (const iface of interfaces[name]) {
            if (iface.family === 'IPv4' && !iface.internal) {
                return iface.address;
            }
        }
    }
    return '127.0.0.1';
}

app.listen(port, '0.0.0.0', () => {
    const ip = getLocalIp();
    console.log('====================================');
    console.log(" Adam's Apartment Hub & Print Server is Running!");
    console.log('====================================');
    console.log(`Open on this PC to test: http://localhost:${port}`);
    console.log(`On your Phone (WiFi): http://${ip}:${port}`);
    console.log('====================================');
});
